loaders:
  - type: haystack_pydoc_tools.loaders.CustomPythonLoader
    search_path: [../src]
    modules:
      [
        "haystack_integrations.components.evaluators.uptrain.evaluator",
        "haystack_integrations.components.evaluators.uptrain.metrics",
      ]
    ignore_when_discovered: ["__init__"]
processors:
  - type: filter
    expression:
    documented_only: true
    do_not_filter_modules: false
    skip_empty_modules: true
  - type: filter
    expression: "name not in ['MetricResult', 'MetricDescriptor', 'OutputConverters', 'InputConverters', 'METRIC_DESCRIPTORS']"
  - type: smart
  - type: crossref
renderer:
  type: haystack_pydoc_tools.renderers.ReadmePreviewRenderer
  excerpt: UpTrain integration for Haystack
  category_slug: integrations-api
  title: UpTrain
  slug: integrations-uptrain
  order: 240
  markdown:
    descriptive_class_title: false
    classdef_code_block: false
    descriptive_module_title: true
    add_method_class_prefix: true
    add_member_class_prefix: false
    filename: _readme_uptrain.md
