version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 1

  - package-ecosystem: 'pip'
    directories:
      - 'integrations/*'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 1
