loaders:
  - modules:
      - haystack_integrations.components.websearch.serperdev.websearch
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: SerperDev integration for Haystack
  id: integrations-serperdev
  filename: serperdev.md
  title: SerperDev
