# SPDX-FileCopyrightText: 2026-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0

import hashlib
from dataclasses import asdict, dataclass, field
from typing import Any


def content_digest(payload: str) -> str:
    """
    Return a short, stable digest of serialized content.

    :param payload: The serialized content to identify.
    :returns: A twelve-character hexadecimal digest.
    """
    return hashlib.sha256(payload.encode()).hexdigest()[:12]


@dataclass(kw_only=True)
class ModelTokenUsage:
    """
    Raw token usage attributable to one model deployment.

    :param input_tokens: Number of input tokens consumed by the model.
    :param output_tokens: Number of output tokens generated by the model.
    """

    input_tokens: int = 0
    output_tokens: int = 0


@dataclass(kw_only=True)
class EvaluationMetrics:
    """
    Measurements produced by a harness evaluator for one Agent configuration.

    :param quality: Normalized aggregate quality score in the inclusive range `[0.0, 1.0]`. Each harness evaluator
        defines which checks contribute to this score.
    :param latency_ms: Mean end-to-end evaluation latency in milliseconds.
    :param model_usage: Raw token usage keyed by model identifier.
    :param cost: Cost derived from `model_usage`, or `None` when usage has not been priced or includes an unknown model.
    :param details: Evaluator-specific measurements and diagnostic information.
    """

    quality: float
    latency_ms: float
    model_usage: dict[str, ModelTokenUsage] = field(default_factory=dict)
    cost: float | None = None
    details: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate the shared normalized quality contract."""
        if not 0.0 <= self.quality <= 1.0:
            msg = "quality must be between 0.0 and 1.0."
            raise ValueError(msg)

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-compatible representation."""
        return {
            "quality": self.quality,
            "latency_ms": self.latency_ms,
            "model_usage": {model: asdict(obj=usage) for model, usage in self.model_usage.items()},
            "cost": self.cost,
            "details": self.details,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "EvaluationMetrics":
        """
        Restore metrics from a serialized representation.

        :param data: Serialized evaluation metrics.
        :returns: The restored evaluation metrics.
        """
        cost = data.get("cost")
        return cls(
            quality=float(data["quality"]),
            latency_ms=float(data["latency_ms"]),
            model_usage={model: ModelTokenUsage(**usage) for model, usage in (data.get("model_usage") or {}).items()},
            cost=None if cost is None else float(cost),
            details=data.get("details") or {},
        )
