# SPDX-FileCopyrightText: 2026-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0

import hashlib
import json
from dataclasses import asdict, dataclass, field
from typing import Any

from haystack import Pipeline
from haystack.components.agents import Agent
from haystack.utils import _deserialize_value_with_schema, _serialize_value_with_schema


def content_digest(payload: str) -> str:
    """
    Return a short, stable digest of serialized content.

    Digests identify configurations, measurements and runs, and they are read by people: in journal records, in
    reports and in logs. Twelve hexadecimal characters separate the few dozen things one experiment distinguishes
    with room to spare, and a full hash only makes those files harder to read.

    :param payload: The serialized content to identify.
    :returns: A twelve-character hexadecimal digest.
    """
    return hashlib.sha256(payload.encode()).hexdigest()[:12]


# What an experiment measures and optimizes. Both are serialized as one Haystack Pipeline YAML and expose the same
# `warm_up`/`close` lifecycle, so an evaluator and the experiment loop treat them alike; an Agent is the special
# case that is wrapped in a one-component Pipeline to be serialized at all.
Optimizable = Agent | Pipeline


@dataclass(frozen=True, kw_only=True)
class AgentRunRecord:
    """
    Inputs and outputs of one successful Agent run.

    This is deliberately not a tracing abstraction. Optimization needs examples it can replay and compare, not the
    span hierarchy produced while an example ran.

    :param run_id: Stable identifier for the run.
    :param inputs: Keyword arguments passed to `Agent.run`.
    :param outputs: Dictionary returned by `Agent.run`.
    """

    run_id: str
    inputs: dict[str, Any]
    outputs: dict[str, Any]

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-compatible representation of the record."""
        return {
            "run_id": self.run_id,
            "inputs": _serialize_value_with_schema(payload=self.inputs),
            "outputs": _serialize_value_with_schema(payload=self.outputs),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AgentRunRecord":
        """
        Restore a serialized run record.

        :param data: Serialized run record created by :meth:`to_dict`.
        :returns: The restored run record.
        """
        inputs = _deserialize_value_with_schema(serialized=data["inputs"])
        outputs = _deserialize_value_with_schema(serialized=data["outputs"])
        return cls(run_id=data["run_id"], inputs=inputs, outputs=outputs)

    def fingerprint(self) -> str:
        """Return a content fingerprint used to invalidate stale experiment measurements."""
        serialized = self.to_dict()
        payload = json.dumps(
            {"inputs": serialized["inputs"], "outputs": serialized["outputs"]}, sort_keys=True, default=str
        )
        return content_digest(payload=payload)


@dataclass(frozen=True, kw_only=True)
class ModelTokenUsage:
    """
    Raw token usage attributable to one model deployment.

    :param input_tokens: Number of input tokens consumed by the model.
    :param output_tokens: Number of output tokens generated by the model.
    """

    input_tokens: int = 0
    output_tokens: int = 0


@dataclass(frozen=True, kw_only=True)
class EvaluationMetrics:
    """
    Measurements produced by a harness evaluator for one Agent configuration.

    :param quality: Normalized aggregate quality score in the inclusive range `[0.0, 1.0]`. Each harness evaluator
        defines which checks contribute to this score.
    :param latency_ms: Mean end-to-end evaluation latency in milliseconds.
    :param model_usage: Raw token usage keyed by model identifier.
    :param cost: Cost derived from `model_usage`, or `None` when usage has not been priced or includes an unknown model.
    :param details: Evaluator-specific measurements and diagnostic information.
    """

    quality: float
    latency_ms: float
    model_usage: dict[str, ModelTokenUsage] = field(default_factory=dict)
    cost: float | None = None
    details: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate the shared normalized quality contract."""
        if not 0.0 <= self.quality <= 1.0:
            msg = "quality must be between 0.0 and 1.0."
            raise ValueError(msg)

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-compatible representation."""
        return {
            "quality": self.quality,
            "latency_ms": self.latency_ms,
            "model_usage": {model: asdict(obj=usage) for model, usage in self.model_usage.items()},
            "cost": self.cost,
            "details": self.details,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "EvaluationMetrics":
        """
        Restore metrics from a serialized representation.

        :param data: Serialized evaluation metrics.
        :returns: The restored evaluation metrics.
        """
        cost = data.get("cost")
        return cls(
            quality=float(data["quality"]),
            latency_ms=float(data["latency_ms"]),
            model_usage={model: ModelTokenUsage(**usage) for model, usage in (data.get("model_usage") or {}).items()},
            cost=None if cost is None else float(cost),
            details=data.get("details") or {},
        )
