services:
  unstructured-api:
    image: "quay.io/unstructured-io/unstructured-api:latest"
    ports:
      - 8000:8000
    restart: on-failure
    healthcheck:
        test: curl --fail http://localhost:8000/healthcheck || exit 1
        interval: 10s
        timeout: 1s
        retries: 10