# SPDX-FileCopyrightText: 2022-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0


class AmazonTextractError(Exception):
    """Any error generated by the Amazon Textract integration."""


class AmazonTextractConfigurationError(AmazonTextractError):
    """Exception raised when AWS is not configured correctly for Textract."""
