services:
  arangodb:
    image: "arangodb:3.12"
    command: ["arangod", "--vector-index"]
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=test-password
    healthcheck:
      test: curl --fail http://localhost:8529/_api/version || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
