loaders:
  - modules:
      - haystack_integrations.components.websearch.linkup.linkup_websearch
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Linkup integration for Haystack
  id: integrations-linkup
  filename: linkup.md
  title: Linkup
