loaders:
  - modules:
      - haystack_integrations.components.classifiers.laya.document_classifier
      - haystack_integrations.components.routers.laya.text_router
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Laya integration for Haystack
  id: integrations-laya
  filename: laya.md
  title: Laya
