loaders:
  - modules:
      - haystack_integrations.components.converters.docling.converter
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Docling integration for Haystack
  id: integrations-docling
  filename: docling.md
  title: Docling
