import json
from typing import Any, ClassVar

from haystack import component, default_from_dict, default_to_dict, logging
from haystack.dataclasses import ChatMessage
from haystack.dataclasses.streaming_chunk import StreamingChunk
from haystack.utils import Secret

logger = logging.getLogger(__name__)


def _convert_messages_to_openai_format(messages: list[ChatMessage]) -> list[dict[str, Any]]:
    """
    Convert Haystack ChatMessage objects to OpenAI-compatible format.

    :param messages: List of ChatMessage objects
    :returns: List of messages in OpenAI format
    """
    result = []
    for msg in messages:
        if msg.role == "system":
            result.append({"role": "system", "content": msg.text})
        elif msg.role == "user":
            result.append({"role": "user", "content": msg.text})
        elif msg.role == "assistant":
            result.append({"role": "assistant", "content": msg.text})
        elif msg.role == "tool":
            result.append({
                "role": "tool",
                "tool_call_id": msg.tool_calls[0].id if msg.tool_calls else "unknown",
                "content": msg.text
            })
    return result


def _convert_response_to_message(response: dict[str, Any]) -> ChatMessage:
    """
    Convert ModelsLab API response to Haystack ChatMessage.

    :param response: Response from ModelsLab API
    :returns: ChatMessage object
    """
    choice = response.get("choices", [{}])[0]
    message = choice.get("message", {})

    content = message.get("content", "")
    role = message.get("role", "assistant")

    # Extract usage info if available
    usage = response.get("usage", {})
    meta = {
        "model": response.get("model", ""),
        "usage": usage,
    }

    return ChatMessage.from_assistant(text=content, meta=meta)


@component
class ModelsLabChatGenerator:
    """
    Completes chats using ModelsLab's large language models.

    It uses [ChatMessage](https://docs.haystack.deepset.ai/docs/data-classes#chatmessage)
    format in input and output.

    You can customize how the text is generated by passing parameters to the
    ModelsLab API. Use the `**generation_kwargs` argument when you initialize
    the component or when you run it.

    Usage example:
    ```python
    from haystack_integrations.components.generators.modelslab import (
        ModelsLabChatGenerator,
    )
    from haystack.dataclasses import ChatMessage

    generator = ModelsLabChatGenerator(
        generation_kwargs={
            "max_tokens": 1000,
            "temperature": 0.7,
        },
    )

    messages = [
        ChatMessage.from_system("You are a helpful assistant"),
        ChatMessage.from_user("What is Python?"),
    ]
    print(generator.run(messages=messages))
    ```
    """

    # Default model
    DEFAULT_MODEL: ClassVar[str] = "meta-llama/Meta-Llama-3.1-70B-Instruct"

    # API endpoint
    API_BASE_URL: ClassVar[str] = "https://modelslab.com/api/v6"

    def __init__(
        self,
        api_key: Secret = Secret.from_env_var("MODELSLAB_API_KEY"),
        model: str = DEFAULT_MODEL,
        generation_kwargs: dict[str, Any] | None = None,
        *,
        timeout: float = 60.0,
    ):
        """
        Creates an instance of ModelsLabChatGenerator.

        :param api_key: The ModelsLab API key
        :param model: The name of the model to use
        :param generation_kwargs: Additional parameters for the API
        :param timeout: Timeout for API calls in seconds
        """
        self.api_key = api_key
        self.model = model
        self.generation_kwargs = generation_kwargs or {}
        self.timeout = timeout

    def to_dict(self) -> dict[str, Any]:
        """
        Serialize this component to a dictionary.

        :returns: The serialized component as a dictionary.
        """
        return default_to_dict(
            self,
            model=self.model,
            generation_kwargs=self.generation_kwargs,
            api_key=self.api_key.to_dict(),
            timeout=self.timeout,
        )

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ModelsLabChatGenerator":
        """
        Deserialize this component from a dictionary.

        :param data: The dictionary representation of this component
        :returns: The deserialized component instance
        """
        data["init_parameters"]["api_key"] = Secret.from_dict(
            data["init_parameters"]["api_key"]
        )
        return default_from_dict(cls, data)

    def _get_telemetry_data(self) -> dict[str, Any]:
        """
        Data that is sent to Posthog for usage analytics.
        """
        return {"model": self.model}

    @component.output_types(replies=list[ChatMessage])
    def run(self, messages: list[ChatMessage], **generation_kwargs) -> dict[str, list[ChatMessage]]:
        """
        Generate chat completions for the given messages.

        :param messages: List of ChatMessage objects
        :param generation_kwargs: Additional generation parameters
        :returns: Dictionary with generated replies
        """
        # Merge generation kwargs
        merged_kwargs = {**self.generation_kwargs, **generation_kwargs}

        # Prepare request payload
        payload = {
            "model": self.model,
            "messages": _convert_messages_to_openai_format(messages),
            "key": self.api_key.resolve_value(),
            **merged_kwargs,
        }

        # Make API request
        try:
            import httpx
            with httpx.Client(timeout=self.timeout) as client:
                response = client.post(
                    f"{self.API_BASE_URL}/chat/completions",
                    json=payload,
                )
                response.raise_for_status()
                result = response.json()
        except httpx.HTTPStatusError as e:
            logger.error("ModelsLab API error: %s", e.response.text)
            raise
        except Exception as e:
            logger.error("Error calling ModelsLab API: %s", str(e))
            raise

        # Convert response to ChatMessage
        message = _convert_response_to_message(result)
        return {"replies": [message]}
