"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2
import sys
import typing

if sys.version_info >= (3, 13):
    import typing as typing_extensions
else:
    import typing_extensions

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str
_InfoInfoType = typing_extensions.TypeVar(
    '_InfoInfoType',
    grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoResponse,
    ],
)

class InfoStub(typing.Generic[_InfoInfoType]):
    @typing.overload
    def __init__(self: InfoStub[
        grpc.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: InfoStub[
        grpc.aio.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Info: _InfoInfoType

InfoAsyncStub: typing_extensions.TypeAlias = InfoStub[
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoResponse,
    ],
]

class InfoServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Info(
        self,
        request: haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoRequest,
        context: _ServicerContext,
    ) -> typing.Union[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoResponse, collections.abc.Awaitable[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.InfoResponse]]: ...

def add_InfoServicer_to_server(servicer: InfoServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...

_EmbedEmbedType = typing_extensions.TypeVar(
    '_EmbedEmbedType',
    grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse,
    ],
)

_EmbedEmbedStreamType = typing_extensions.TypeVar(
    '_EmbedEmbedStreamType',
    grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse,
    ],
    default=grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse,
    ],
)

_EmbedEmbedSparseType = typing_extensions.TypeVar(
    '_EmbedEmbedSparseType',
    grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse,
    ],
)

_EmbedEmbedSparseStreamType = typing_extensions.TypeVar(
    '_EmbedEmbedSparseStreamType',
    grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse,
    ],
    default=grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse,
    ],
)

_EmbedEmbedAllType = typing_extensions.TypeVar(
    '_EmbedEmbedAllType',
    grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse,
    ],
)

_EmbedEmbedAllStreamType = typing_extensions.TypeVar(
    '_EmbedEmbedAllStreamType',
    grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse,
    ],
    default=grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse,
    ],
)

class EmbedStub(typing.Generic[_EmbedEmbedType, _EmbedEmbedStreamType, _EmbedEmbedSparseType, _EmbedEmbedSparseStreamType, _EmbedEmbedAllType, _EmbedEmbedAllStreamType]):
    @typing.overload
    def __init__(self: EmbedStub[
        grpc.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse,
        ],
        grpc.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse,
        ],
        grpc.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse,
        ],
        grpc.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: EmbedStub[
        grpc.aio.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse,
        ],
        grpc.aio.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse,
        ],
        grpc.aio.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse,
        ],
        grpc.aio.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Embed: _EmbedEmbedType

    EmbedStream: _EmbedEmbedStreamType

    EmbedSparse: _EmbedEmbedSparseType

    EmbedSparseStream: _EmbedEmbedSparseStreamType

    EmbedAll: _EmbedEmbedAllType

    EmbedAllStream: _EmbedEmbedAllStreamType

EmbedAsyncStub: typing_extensions.TypeAlias = EmbedStub[
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse,
    ],
]

class EmbedServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Embed(
        self,
        request: haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest,
        context: _ServicerContext,
    ) -> typing.Union[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse, collections.abc.Awaitable[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse]]: ...

    @abc.abstractmethod
    def EmbedStream(
        self,
        request_iterator: _MaybeAsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedRequest],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse], collections.abc.AsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedResponse]]: ...

    @abc.abstractmethod
    def EmbedSparse(
        self,
        request: haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest,
        context: _ServicerContext,
    ) -> typing.Union[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse, collections.abc.Awaitable[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse]]: ...

    @abc.abstractmethod
    def EmbedSparseStream(
        self,
        request_iterator: _MaybeAsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseRequest],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse], collections.abc.AsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedSparseResponse]]: ...

    @abc.abstractmethod
    def EmbedAll(
        self,
        request: haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest,
        context: _ServicerContext,
    ) -> typing.Union[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse, collections.abc.Awaitable[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse]]: ...

    @abc.abstractmethod
    def EmbedAllStream(
        self,
        request_iterator: _MaybeAsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllRequest],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse], collections.abc.AsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EmbedAllResponse]]: ...

def add_EmbedServicer_to_server(servicer: EmbedServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...

_PredictPredictType = typing_extensions.TypeVar(
    '_PredictPredictType',
    grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
)

_PredictPredictPairType = typing_extensions.TypeVar(
    '_PredictPredictPairType',
    grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
)

_PredictPredictStreamType = typing_extensions.TypeVar(
    '_PredictPredictStreamType',
    grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
    default=grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
)

_PredictPredictPairStreamType = typing_extensions.TypeVar(
    '_PredictPredictPairStreamType',
    grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
    default=grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
)

class PredictStub(typing.Generic[_PredictPredictType, _PredictPredictPairType, _PredictPredictStreamType, _PredictPredictPairStreamType]):
    @typing.overload
    def __init__(self: PredictStub[
        grpc.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
        ],
        grpc.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
        ],
        grpc.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: PredictStub[
        grpc.aio.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
        ],
        grpc.aio.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
        ],
        grpc.aio.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Predict: _PredictPredictType

    PredictPair: _PredictPredictPairType

    PredictStream: _PredictPredictStreamType

    PredictPairStream: _PredictPredictPairStreamType

PredictAsyncStub: typing_extensions.TypeAlias = PredictStub[
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse,
    ],
]

class PredictServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Predict(
        self,
        request: haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest,
        context: _ServicerContext,
    ) -> typing.Union[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse, collections.abc.Awaitable[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse]]: ...

    @abc.abstractmethod
    def PredictPair(
        self,
        request: haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest,
        context: _ServicerContext,
    ) -> typing.Union[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse, collections.abc.Awaitable[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse]]: ...

    @abc.abstractmethod
    def PredictStream(
        self,
        request_iterator: _MaybeAsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictRequest],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse], collections.abc.AsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse]]: ...

    @abc.abstractmethod
    def PredictPairStream(
        self,
        request_iterator: _MaybeAsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictPairRequest],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse], collections.abc.AsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.PredictResponse]]: ...

def add_PredictServicer_to_server(servicer: PredictServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...

_RerankRerankType = typing_extensions.TypeVar(
    '_RerankRerankType',
    grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse,
    ],
)

_RerankRerankStreamType = typing_extensions.TypeVar(
    '_RerankRerankStreamType',
    grpc.StreamUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankStreamRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse,
    ],
    grpc.aio.StreamUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankStreamRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse,
    ],
    default=grpc.StreamUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankStreamRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse,
    ],
)

class RerankStub(typing.Generic[_RerankRerankType, _RerankRerankStreamType]):
    @typing.overload
    def __init__(self: RerankStub[
        grpc.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse,
        ],
        grpc.StreamUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankStreamRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: RerankStub[
        grpc.aio.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse,
        ],
        grpc.aio.StreamUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankStreamRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Rerank: _RerankRerankType

    RerankStream: _RerankRerankStreamType

RerankAsyncStub: typing_extensions.TypeAlias = RerankStub[
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse,
    ],
    grpc.aio.StreamUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankStreamRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse,
    ],
]

class RerankServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Rerank(
        self,
        request: haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankRequest,
        context: _ServicerContext,
    ) -> typing.Union[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse, collections.abc.Awaitable[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse]]: ...

    @abc.abstractmethod
    def RerankStream(
        self,
        request_iterator: _MaybeAsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankStreamRequest],
        context: _ServicerContext,
    ) -> typing.Union[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse, collections.abc.Awaitable[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.RerankResponse]]: ...

def add_RerankServicer_to_server(servicer: RerankServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...

_TokenizeTokenizeType = typing_extensions.TypeVar(
    '_TokenizeTokenizeType',
    grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse,
    ],
)

_TokenizeTokenizeStreamType = typing_extensions.TypeVar(
    '_TokenizeTokenizeStreamType',
    grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse,
    ],
    default=grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse,
    ],
)

_TokenizeDecodeType = typing_extensions.TypeVar(
    '_TokenizeDecodeType',
    grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse,
    ],
    default=grpc.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse,
    ],
)

_TokenizeDecodeStreamType = typing_extensions.TypeVar(
    '_TokenizeDecodeStreamType',
    grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse,
    ],
    default=grpc.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse,
    ],
)

class TokenizeStub(typing.Generic[_TokenizeTokenizeType, _TokenizeTokenizeStreamType, _TokenizeDecodeType, _TokenizeDecodeStreamType]):
    @typing.overload
    def __init__(self: TokenizeStub[
        grpc.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse,
        ],
        grpc.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse,
        ],
        grpc.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse,
        ],
        grpc.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse,
        ],
    ], channel: grpc.Channel) -> None: ...

    @typing.overload
    def __init__(self: TokenizeStub[
        grpc.aio.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse,
        ],
        grpc.aio.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse,
        ],
        grpc.aio.UnaryUnaryMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse,
        ],
        grpc.aio.StreamStreamMultiCallable[
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest,
            haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse,
        ],
    ], channel: grpc.aio.Channel) -> None: ...

    Tokenize: _TokenizeTokenizeType

    TokenizeStream: _TokenizeTokenizeStreamType

    Decode: _TokenizeDecodeType

    DecodeStream: _TokenizeDecodeStreamType

TokenizeAsyncStub: typing_extensions.TypeAlias = TokenizeStub[
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse,
    ],
    grpc.aio.UnaryUnaryMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse,
    ],
    grpc.aio.StreamStreamMultiCallable[
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest,
        haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse,
    ],
]

class TokenizeServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Tokenize(
        self,
        request: haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest,
        context: _ServicerContext,
    ) -> typing.Union[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse, collections.abc.Awaitable[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse]]: ...

    @abc.abstractmethod
    def TokenizeStream(
        self,
        request_iterator: _MaybeAsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeRequest],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse], collections.abc.AsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.EncodeResponse]]: ...

    @abc.abstractmethod
    def Decode(
        self,
        request: haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest,
        context: _ServicerContext,
    ) -> typing.Union[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse, collections.abc.Awaitable[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse]]: ...

    @abc.abstractmethod
    def DecodeStream(
        self,
        request_iterator: _MaybeAsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeRequest],
        context: _ServicerContext,
    ) -> typing.Union[collections.abc.Iterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse], collections.abc.AsyncIterator[haystack_integrations.components.embedders.huggingface_api._grpc.tei_pb2.DecodeResponse]]: ...

def add_TokenizeServicer_to_server(servicer: TokenizeServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
