[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "farm-haystack-mongodb-documentstore"
description = ''
readme = "README.md"
requires-python = ">=3.7"
license = "Apache-2.0"
keywords = []
authors = [{ name = "deepset GmbH", email = "info@deepset.ai" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["farm-haystack>1, <2", "pymongo<5"]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["farm-haystack[dev]>1, <2"]

[project.urls]
Documentation = "https://github.com/unknown/mongodb-documentstore#readme"
Issues = "https://github.com/unknown/mongodb-documentstore/issues"
Source = "https://github.com/unknown/mongodb-documentstore"

[tool.hatch.version]
path = "mongodb_documentstore/__about__.py"

[tool.hatch.envs.default]
dependencies = ["pytest", "pytest-cov"]

[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=mongodb_documentstore --cov=tests"
no-cov = "cov --no-cov"

[[tool.hatch.envs.test.matrix]]
python = ["37", "38", "39", "310", "311"]

[tool.coverage.run]
branch = true
parallel = true
omit = ["mongodb_documentstore/__about__.py"]

[tool.coverage.report]
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]
