loaders:
  - modules:
      - haystack_integrations.components.websearch.scavio.scavio_websearch
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Scavio integration for Haystack
  id: integrations-scavio
  filename: scavio.md
  title: Scavio
