services:
  tei-sparse:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.9.3
    command: ["--model-id", "opensearch-project/opensearch-neural-sparse-encoding-doc-v2-mini", "--pooling", "splade"]
    ports:
      - "8080:80"
    environment:
      - HF_TOKEN
    volumes:
      - tei-data:/data
    restart: no

volumes:
  tei-data:
