# SPDX-FileCopyrightText: 2026-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0

from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any, Literal

from haystack import Document, component, default_from_dict, default_to_dict
from haystack.dataclasses import ByteStream

import opendataloader_pdf  # type: ignore[import-untyped]

OutputFormat = Literal["markdown", "text", "json", "html"]


@component
class OpenDataLoaderConverter:
    """
    OpenDataLoader PDF converter component.

    The component accepts PDF file paths and Haystack ByteStream objects,
    runs OpenDataLoader PDF extraction, and returns Haystack Document objects.

    :param output_format:
        Output format generated by OpenDataLoader.
        Supported formats are markdown, text, json, and html.

    :param convert_kwargs:
        Additional arguments passed to OpenDataLoader PDF.
    """

    def __init__(
        self,
        *,
        output_format: OutputFormat = "markdown",
        convert_kwargs: dict[str, Any] | None = None,
    ) -> None:
        """
        Initialize the OpenDataLoader converter.

        :param output_format:
            Format OpenDataLoader should produce.

        :param convert_kwargs:
            Additional OpenDataLoader conversion options.
        """
        self.output_format = output_format
        self.convert_kwargs = convert_kwargs or {}

    def to_dict(self) -> dict[str, Any]:
        """
        Serialize the component.

        :returns:
            Dictionary representation of the converter.
        """
        return default_to_dict(
            self,
            output_format=self.output_format,
            convert_kwargs=self.convert_kwargs,
        )

    @classmethod
    def from_dict(
        cls,
        data: dict[str, Any],
    ) -> "OpenDataLoaderConverter":
        """
        Deserialize the component.

        :param data:
            Serialized component dictionary.

        :returns:
            Reconstructed OpenDataLoaderConverter.
        """
        return default_from_dict(cls, data)

    def _prepare_sources(
        self,
        sources: list[str | Path | ByteStream],
        temp_dir: Path,
    ) -> list[Path]:
        """
        Convert input sources into PDF file paths.

        ByteStream inputs are written to temporary files because
        OpenDataLoader expects file paths.
        """
        pdf_paths = []
        for idx, source in enumerate(sources):
            if isinstance(source, ByteStream):
                pdf_path = temp_dir / f"document_{idx}.pdf"
                pdf_path.write_bytes(source.data)

            else:
                pdf_path = Path(source)

            if pdf_path.suffix.lower() != ".pdf":
                message = f"OpenDataLoaderConverter only supports PDFs: {pdf_path}"

                raise ValueError(message)

            pdf_paths.append(pdf_path)

        return pdf_paths

    def _read_output(
        self,
        output_dir: Path,
        pdf_path: Path,
    ) -> str:
        """
        Read the OpenDataLoader output file.

        :param output_dir:
            Directory containing converted files.

        :param pdf_path:
            Original PDF path used to determine the output filename.

        :returns:
            Extracted document content.
        """
        extension_map = {
            "markdown": "md",
            "text": "txt",
            "html": "html",
            "json": "json",
        }
        extension = extension_map[self.output_format]
        output_file = output_dir / (f"{pdf_path.stem}.{extension}")
        if not output_file.exists():
            message = f"OpenDataLoader did not create expected file: {output_file}"

            raise RuntimeError(message)
        return output_file.read_text(encoding="utf-8")

    @component.output_types(documents=list[Document])
    def run(
        self,
        sources: list[str | Path | ByteStream],
        meta: dict[str, Any] | None = None,
    ) -> dict[str, list[Document]]:
        """
        Convert PDF sources into Haystack Documents.

        :param sources:
            PDF file paths or Haystack ByteStream objects.

        :param meta:
            Optional metadata added to generated Documents.

        :returns:
            Dictionary containing the converted Documents.
        """
        documents = []
        if not sources:
            return {"documents": []}
        with TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            input_dir = tmp_path / "input"
            output_dir = tmp_path / "output"
            input_dir.mkdir()
            output_dir.mkdir()

            pdf_paths = self._prepare_sources(
                sources,
                input_dir,
            )

            opendataloader_pdf.convert(
                input_path=[str(path) for path in pdf_paths],
                output_dir=str(output_dir),
                format=self.output_format,
                **self.convert_kwargs,
            )

            for pdf_path in pdf_paths:
                content = self._read_output(
                    output_dir,
                    pdf_path,
                )
                documents.append(
                    Document(
                        content=content,
                        meta={
                            "file_path": pdf_path.name,
                            "output_format": self.output_format,
                            **(meta or {}),
                        },
                    )
                )
        return {"documents": documents}
