loaders:
  - modules:
      - haystack_integrations.components.preprocessors.chonkie.recursive_splitter
      - haystack_integrations.components.preprocessors.chonkie.semantic_splitter
      - haystack_integrations.components.preprocessors.chonkie.sentence_splitter
      - haystack_integrations.components.preprocessors.chonkie.token_splitter
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Chonkie integration for Haystack
  id: integrations-chonkie
  filename: chonkie.md
  title: Chonkie
