loaders:
  - modules:
      - haystack_integrations.components.embedders.voyage.text_embedder
      - haystack_integrations.components.embedders.voyage.document_embedder
      - haystack_integrations.components.embedders.voyage.contextualized_document_embedder
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Voyage integration for Haystack
  id: integrations-voyage
  filename: voyage.md
  title: Voyage
