import inspect
from datetime import datetime, timezone
from typing import Any, ClassVar

from haystack import component, default_from_dict, default_to_dict, logging
from haystack.components.generators.utils import _convert_streaming_chunks_to_chat_message, _normalize_messages
from haystack.dataclasses.chat_message import ChatMessage
from haystack.dataclasses.streaming_chunk import (
    ComponentInfo,
    StreamingCallbackT,
    StreamingChunk,
    SyncStreamingCallbackT,
    select_streaming_callback,
)
from haystack.tools import (
    ToolsType,
    _check_duplicate_tool_names,
    deserialize_tools_or_toolset_inplace,
    flatten_tools_or_toolsets,
    serialize_tools_or_toolset,
)
from haystack.utils.auth import Secret, deserialize_secrets_inplace
from haystack.utils.callable_serialization import deserialize_callable, serialize_callable

from anthropic import Anthropic, AsyncAnthropic
from anthropic.resources.messages.messages import Message, RawMessageStreamEvent, Stream
from anthropic.types import (
    MessageParam,
    TextBlockParam,
    ToolParam,
)

from .utils import (
    _accumulate_raw_content_blocks,
    _convert_anthropic_chunk_to_streaming_chunk,
    _convert_chat_completion_to_chat_message,
    _convert_messages_to_anthropic_format,
    _extract_citations,
    _has_server_tool_blocks,
    _process_reasoning_contents,
)

logger = logging.getLogger(__name__)


@component
class AnthropicChatGenerator:
    """
    Completes chats using Anthropic's large language models (LLMs).

    It uses [ChatMessage](https://docs.haystack.deepset.ai/docs/data-classes#chatmessage)
    format in input and output. Supports multimodal inputs including text and images.

    You can customize how the text is generated by passing parameters to the
    Anthropic API. Use the `**generation_kwargs` argument when you initialize
    the component or when you run it. Any parameter that works with
    `anthropic.Message.create` will work here too.

    For details on Anthropic API parameters, see
    [Anthropic documentation](https://docs.anthropic.com/en/api/messages).

    Usage example:
    ```python
    from haystack_integrations.components.generators.anthropic import (
        AnthropicChatGenerator,
    )
    from haystack.dataclasses import ChatMessage

    generator = AnthropicChatGenerator(
        generation_kwargs={
            "max_tokens": 1000,
            "temperature": 0.7,
        },
    )

    messages = [
        ChatMessage.from_system(
            "You are a helpful, respectful and honest assistant"
        ),
        ChatMessage.from_user("What's Natural Language Processing?"),
    ]
    print(generator.run(messages=messages))
    ```

    Usage example with images:
    ```python
    from haystack.dataclasses import ChatMessage, ImageContent

    image_content = ImageContent.from_file_path("path/to/image.jpg")
    messages = [
        ChatMessage.from_user(
            content_parts=["What's in this image?", image_content]
        )
    ]
    generator = AnthropicChatGenerator()
    result = generator.run(messages)
    ```
    """

    # The parameters that can be passed to the Anthropic API https://docs.anthropic.com/claude/reference/messages_post
    ALLOWED_PARAMS: ClassVar[list[str]] = [
        "system",
        "tools",
        "tool_choice",
        "max_tokens",
        "metadata",
        "stop_sequences",
        "temperature",
        "top_p",
        "top_k",
        "extra_headers",
        "thinking",
        "output_config",
    ]

    SUPPORTED_MODELS: ClassVar[list[str]] = [
        "claude-opus-4-6",
        "claude-sonnet-4-6",
        "claude-haiku-4-5-20251001",
        "claude-sonnet-4-5-20250929",
        "claude-opus-4-5-20251101",
        "claude-opus-4-1-20250805",
        "claude-sonnet-4-20250514",
        "claude-opus-4-20250514",
        "claude-3-haiku-20240307",
    ]
    """A non-exhaustive list of chat models supported by this component. See
     https://platform.claude.com/docs/en/about-claude/models/overview for the full list."""

    def __init__(
        self,
        api_key: Secret = Secret.from_env_var("ANTHROPIC_API_KEY"),  # noqa: B008
        model: str = "claude-sonnet-4-5",
        streaming_callback: StreamingCallbackT | None = None,
        generation_kwargs: dict[str, Any] | None = None,
        ignore_tools_thinking_messages: bool = True,
        tools: ToolsType | None = None,
        anthropic_server_tools: list[dict[str, Any]] | None = None,
        *,
        timeout: float | None = None,
        max_retries: int | None = None,
    ) -> None:
        """
        Creates an instance of AnthropicChatGenerator.

        :param api_key: The Anthropic API key
        :param model: The name of the model to use.
        :param streaming_callback: A callback function that is called when a new token is received from the stream.
            The callback function accepts StreamingChunk as an argument.
        :param generation_kwargs: Other parameters to use for the model. These parameters are all sent directly to
            the Anthropic endpoint. See Anthropic [documentation](https://docs.anthropic.com/claude/reference/messages_post)
            for more details.

            Supported generation_kwargs parameters are:
            - `system`: The system message to be passed to the model.
            - `max_tokens`: The maximum number of tokens to generate.
            - `metadata`: A dictionary of metadata to be passed to the model.
            - `stop_sequences`: A list of strings that the model should stop generating at.
            - `temperature`: The temperature to use for sampling.
            - `top_p`: The top_p value to use for nucleus sampling.
            - `top_k`: The top_k value to use for top-k sampling.
            - `extra_headers`: A dictionary of extra headers to be passed to the model (i.e. for beta features).
            - `thinking`: A dictionary of thinking parameters to be passed to the model.
                The `budget_tokens` passed for thinking should be less than `max_tokens`.
                For more details and supported models, see: [Anthropic Extended Thinking](https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking)
            - `output_config`: A dictionary of output configuration options to be passed to the model.

        :param ignore_tools_thinking_messages: Anthropic's approach to tools (function calling) resolution involves a
            "chain of thought" messages before returning the actual function names and parameters in a message. If
            `ignore_tools_thinking_messages` is `True`, the generator will drop so-called thinking messages when tool
            use is detected. See the Anthropic [tools](https://docs.anthropic.com/en/docs/tool-use#chain-of-thought-tool-use)
            for more details.
        :param tools: A list of Tool and/or Toolset objects, or a single Toolset, that the model can use.
            Each tool should have a unique name.
        :param anthropic_server_tools: A list of Anthropic server-side tools passed directly to the API.
            Use this for native Anthropic tools such as web search (`{"type": "web_search_20250305"}`),
            code execution tool, or other provider-managed tools. Refer to the
            [Anthropic documentation](https://docs.anthropic.com/en/docs/agents-and-tools/tool-use/web-search-tool)
            for the exact dict format each native tool expects.
        :param timeout:
            Timeout for Anthropic client calls. If not set, it defaults to the default set by the Anthropic client.
        :param max_retries:
            Maximum number of retries to attempt for failed requests. If not set, it defaults to the default set by
            the Anthropic client.

        """
        _check_duplicate_tool_names(flatten_tools_or_toolsets(tools))

        self.api_key = api_key
        self.model = model
        self.generation_kwargs = generation_kwargs or {}
        self.streaming_callback = streaming_callback
        self.timeout = timeout
        self.max_retries = max_retries

        client_kwargs: dict[str, Any] = {"api_key": api_key.resolve_value()}
        # We do this since timeout=None is not the same as not setting it in Anthropic
        if timeout is not None:
            client_kwargs["timeout"] = timeout
        # We do this since max_retries must be an int when passing to Anthropic
        if max_retries is not None:
            client_kwargs["max_retries"] = max_retries

        self.client = Anthropic(**client_kwargs)
        self.async_client = AsyncAnthropic(**client_kwargs)

        self.ignore_tools_thinking_messages = ignore_tools_thinking_messages
        self.tools = tools
        self.anthropic_server_tools = anthropic_server_tools

    def _get_telemetry_data(self) -> dict[str, Any]:
        """
        Data that is sent to Posthog for usage analytics.
        """
        return {"model": self.model}

    def to_dict(self) -> dict[str, Any]:
        """
        Serialize this component to a dictionary.

        :returns:
            The serialized component as a dictionary.
        """
        callback_name = serialize_callable(self.streaming_callback) if self.streaming_callback else None
        return default_to_dict(
            self,
            model=self.model,
            streaming_callback=callback_name,
            generation_kwargs=self.generation_kwargs,
            api_key=self.api_key.to_dict(),
            ignore_tools_thinking_messages=self.ignore_tools_thinking_messages,
            tools=serialize_tools_or_toolset(self.tools),
            anthropic_server_tools=self.anthropic_server_tools,
            timeout=self.timeout,
            max_retries=self.max_retries,
        )

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "AnthropicChatGenerator":
        """
        Deserialize this component from a dictionary.

        :param data: The dictionary representation of this component.
        :returns:
            The deserialized component instance.
        """
        deserialize_secrets_inplace(data["init_parameters"], keys=["api_key"])
        deserialize_tools_or_toolset_inplace(data["init_parameters"], key="tools")
        init_params = data.get("init_parameters", {})
        serialized_callback_handler = init_params.get("streaming_callback")
        if serialized_callback_handler:
            data["init_parameters"]["streaming_callback"] = deserialize_callable(serialized_callback_handler)

        return default_from_dict(cls, data)

    def _prepare_request_params(
        self,
        messages: list[ChatMessage],
        generation_kwargs: dict[str, Any] | None = None,
        tools: ToolsType | None = None,
    ) -> tuple[list[TextBlockParam], list[MessageParam], dict[str, Any], list[Any]]:
        """
        Prepare the parameters for the Anthropic API request.

        :param messages: A list of ChatMessage instances representing the input messages.
        :param generation_kwargs: Optional arguments to pass to the Anthropic generation endpoint.
        :param tools: A list of Tool and/or Toolset objects, or a single Toolset, that the model can use.
        Each tool should have a unique name.
        :returns: A tuple containing:
            - system_messages: List of system messages in Anthropic format
            - non_system_messages: List of non-system messages in Anthropic format
            - generation_kwargs: Processed generation kwargs
            - anthropic_tools: List of tools in Anthropic format
        """
        # update generation kwargs by merging with the generation kwargs passed to the run method
        generation_kwargs = {**self.generation_kwargs, **(generation_kwargs or {})}
        generation_kwargs = self._resolve_flattened_generation_kwargs(generation_kwargs)

        disallowed_params = set(generation_kwargs) - set(self.ALLOWED_PARAMS)
        if disallowed_params:
            logger.warning(
                "Model parameters {disallowed_params} are not allowed and will be ignored. "
                "Allowed parameters are {allowed_params}.",
                disallowed_params=disallowed_params,
                allowed_params=self.ALLOWED_PARAMS,
            )
        generation_kwargs = {k: v for k, v in generation_kwargs.items() if k in self.ALLOWED_PARAMS}

        system_messages, non_system_messages = _convert_messages_to_anthropic_format(messages)

        # prompt caching

        # tools management
        tools = tools or self.tools
        flattened_tools = flatten_tools_or_toolsets(tools)
        _check_duplicate_tool_names(flattened_tools)

        anthropic_tools: list[Any] = []
        if flattened_tools:
            for tool in flattened_tools:
                anthropic_tools.append(
                    ToolParam(name=tool.name, description=tool.description, input_schema=tool.parameters)
                )
        if self.anthropic_server_tools:
            server_tool_names = {st["name"] for st in self.anthropic_server_tools if "name" in st}
            if duplicates := server_tool_names & {tool.name for tool in flattened_tools}:
                msg = (
                    f"Duplicate tool names found: {sorted(duplicates)}. "
                    "`anthropic_server_tools` cannot reuse a name from `tools`."
                )
                raise ValueError(msg)
            anthropic_tools.extend(self.anthropic_server_tools)

        return system_messages, non_system_messages, generation_kwargs, anthropic_tools

    def _resolve_flattened_generation_kwargs(self, generation_kwargs: dict[str, Any]) -> dict[str, Any]:
        generation_kwargs = generation_kwargs.copy()

        disable_parallel_tool_use = generation_kwargs.pop("disable_parallel_tool_use", None)
        parallel_tool_use = generation_kwargs.pop("parallel_tool_use", None)

        if disable_parallel_tool_use is not None and parallel_tool_use is not None:
            msg = "Cannot set both disable_parallel_tool_use and parallel_tool_use"
            raise ValueError(msg)
        elif parallel_tool_use is not None:
            disable_parallel_tool_use = not parallel_tool_use

        if disable_parallel_tool_use is not None:
            tool_choice = generation_kwargs.setdefault("tool_choice", {})
            tool_choice["disable_parallel_tool_use"] = disable_parallel_tool_use
            tool_choice.setdefault("type", "auto")  # default value

        tool_choice_type = generation_kwargs.pop("tool_choice_type", None)
        if tool_choice_type is not None:
            tool_choice = generation_kwargs.setdefault("tool_choice", {})
            tool_choice["type"] = tool_choice_type

        thinking_budget_tokens = generation_kwargs.pop("thinking_budget_tokens", None)
        if thinking_budget_tokens is not None:
            thinking = generation_kwargs.setdefault("thinking", {})
            thinking["budget_tokens"] = thinking_budget_tokens
            thinking.setdefault("type", "enabled")

        adaptive_thinking_effort = generation_kwargs.pop("adaptive_thinking_effort", None)
        if adaptive_thinking_effort is not None:
            thinking = generation_kwargs.setdefault("thinking", {})
            if adaptive_thinking_effort in ("disabled", "none"):
                thinking.setdefault("type", "disabled")
            else:
                thinking.setdefault("type", "adaptive")
                output_config = generation_kwargs.setdefault("output_config", {})
                output_config["effort"] = adaptive_thinking_effort

        return generation_kwargs

    def _process_response(
        self,
        response: Message | Stream[RawMessageStreamEvent],
        streaming_callback: SyncStreamingCallbackT | None = None,
    ) -> dict[str, list[ChatMessage]]:
        """
        Process the response from the Anthropic API.

        :param response: The response from the Anthropic API.
        :param streaming_callback: A callback function that is called when a new token is received from the stream.
        :returns: A dictionary containing the processed response as a list of ChatMessage objects.
        """
        # workaround for https://github.com/DataDog/dd-trace-py/issues/12562
        # we cannot use isinstance(Stream)
        if not isinstance(response, Message):
            chunks: list[StreamingChunk] = []
            model: str | None = None
            tool_call_index = -1
            in_server_tool_block = False
            input_tokens = None
            component_info = ComponentInfo.from_component(self)
            for chunk in response:
                if chunk.type in ["message_start", "content_block_start", "content_block_delta", "message_delta"]:
                    # Extract model from message_start chunks
                    if chunk.type == "message_start":
                        model = chunk.message.model
                        if chunk.message.usage.input_tokens is not None:
                            input_tokens = chunk.message.usage.input_tokens

                    if chunk.type == "content_block_start":
                        if chunk.content_block.type == "tool_use":
                            tool_call_index += 1
                        # server tools are executed by Anthropic: their streamed input must not become a ToolCall
                        in_server_tool_block = chunk.content_block.type == "server_tool_use"

                    streaming_chunk = _convert_anthropic_chunk_to_streaming_chunk(
                        chunk, component_info, tool_call_index, in_server_tool_block
                    )
                    chunks.append(streaming_chunk)
                    if streaming_callback:
                        streaming_callback(streaming_chunk)

            completion = _convert_streaming_chunks_to_chat_message(chunks)
            reasoning = _process_reasoning_contents(chunks)

            completion.meta.update(
                {"received_at": datetime.now(timezone.utc).isoformat(), "model": model},
            )

            if input_tokens is not None:
                if "usage" not in completion.meta:
                    completion.meta["usage"] = {}
                completion.meta["usage"]["input_tokens"] = input_tokens

            # keep the raw content so server-tool blocks can be replayed on later turns
            if self.anthropic_server_tools:
                raw_content = _accumulate_raw_content_blocks(chunks)
                if _has_server_tool_blocks(raw_content):
                    completion.meta["raw_content_for_server_tools"] = raw_content
                if citations := _extract_citations(raw_content):
                    completion.meta["citations"] = citations

            return {
                "replies": [
                    ChatMessage.from_assistant(
                        text=completion.text,
                        tool_calls=completion.tool_calls,
                        meta=completion.meta,
                        name=completion.name,
                        reasoning=reasoning,
                    )
                ]
            }

        else:
            return {
                "replies": [_convert_chat_completion_to_chat_message(response, self.ignore_tools_thinking_messages)]
            }

    async def _process_response_async(
        self,
        response: Any,
        streaming_callback: StreamingCallbackT | None = None,
    ) -> dict[str, list[ChatMessage]]:
        """
        Process the response from the Anthropic API asynchronously.

        :param response: The response from the Anthropic API.
        :param streaming_callback: A callback function that is called when a new token is received from the stream.

        :returns:
            A dictionary containing the processed response as a list of ChatMessage objects.
        """
        # workaround for https://github.com/DataDog/dd-trace-py/issues/12562
        if not isinstance(response, Message):
            chunks: list[StreamingChunk] = []
            model: str | None = None
            tool_call_index = -1
            in_server_tool_block = False
            input_tokens = None
            component_info = ComponentInfo.from_component(self)
            async for chunk in response:
                if chunk.type in [
                    "message_start",
                    "content_block_start",
                    "content_block_delta",
                    "message_delta",
                ]:
                    # Extract model from message_start chunks
                    if chunk.type == "message_start":
                        model = chunk.message.model
                        if chunk.message.usage.input_tokens is not None:
                            input_tokens = chunk.message.usage.input_tokens

                    if chunk.type == "content_block_start":
                        if chunk.content_block.type == "tool_use":
                            tool_call_index += 1
                        # server tools are executed by Anthropic: their streamed input must not become a ToolCall
                        in_server_tool_block = chunk.content_block.type == "server_tool_use"

                    streaming_chunk = _convert_anthropic_chunk_to_streaming_chunk(
                        chunk, component_info, tool_call_index, in_server_tool_block
                    )
                    chunks.append(streaming_chunk)
                    if streaming_callback:
                        # sync callbacks are allowed in async contexts with Haystack >= 3.0, so only await async ones
                        callback_result = streaming_callback(streaming_chunk)
                        if inspect.isawaitable(callback_result):
                            await callback_result

            completion = _convert_streaming_chunks_to_chat_message(chunks)
            reasoning = _process_reasoning_contents(chunks)

            completion.meta.update(
                {"received_at": datetime.now(timezone.utc).isoformat(), "model": model},
            )

            if input_tokens is not None:
                if "usage" not in completion.meta:
                    completion.meta["usage"] = {}
                completion.meta["usage"]["input_tokens"] = input_tokens

            # keep the raw content so server-tool blocks can be replayed on later turns
            if self.anthropic_server_tools:
                raw_content = _accumulate_raw_content_blocks(chunks)
                if _has_server_tool_blocks(raw_content):
                    completion.meta["raw_content_for_server_tools"] = raw_content
                if citations := _extract_citations(raw_content):
                    completion.meta["citations"] = citations

            return {
                "replies": [
                    ChatMessage.from_assistant(
                        text=completion.text,
                        tool_calls=completion.tool_calls,
                        meta=completion.meta,
                        name=completion.name,
                        reasoning=reasoning,
                    )
                ]
            }
        else:
            return {
                "replies": [_convert_chat_completion_to_chat_message(response, self.ignore_tools_thinking_messages)]
            }

    @component.output_types(replies=list[ChatMessage])
    def run(
        self,
        messages: list[ChatMessage] | str,
        streaming_callback: StreamingCallbackT | None = None,
        generation_kwargs: dict[str, Any] | None = None,
        tools: ToolsType | None = None,
    ) -> dict[str, list[ChatMessage]]:
        """
        Invokes the Anthropic API with the given messages and generation kwargs.

        :param messages: A list of ChatMessage instances representing the input messages.
            If a string is provided, it is converted to a list containing a ChatMessage with user role.
        :param streaming_callback: A callback function that is called when a new token is received from the stream.
        :param generation_kwargs: Optional arguments to pass to the Anthropic generation endpoint.
        :param tools: A list of Tool and/or Toolset objects, or a single Toolset, that the model can use.
        Each tool should have a unique name. If set, it will override the `tools` parameter set during component
        initialization.
        :returns: A dictionary with the following keys:
            - `replies`: The responses from the model
        """
        messages = _normalize_messages(messages)
        system_messages, non_system_messages, generation_kwargs, anthropic_tools = self._prepare_request_params(
            messages, generation_kwargs, tools
        )

        streaming_callback = select_streaming_callback(
            init_callback=self.streaming_callback,
            runtime_callback=streaming_callback,
            requires_async=False,
        )

        response = self.client.messages.create(
            model=self.model,
            messages=non_system_messages,
            system=system_messages,
            tools=anthropic_tools,
            stream=streaming_callback is not None,
            max_tokens=generation_kwargs.pop("max_tokens", 1024),
            **generation_kwargs,
        )

        return self._process_response(response=response, streaming_callback=streaming_callback)

    @component.output_types(replies=list[ChatMessage])
    async def run_async(
        self,
        messages: list[ChatMessage] | str,
        streaming_callback: StreamingCallbackT | None = None,
        generation_kwargs: dict[str, Any] | None = None,
        tools: ToolsType | None = None,
    ) -> dict[str, list[ChatMessage]]:
        """
        Async version of the run method. Invokes the Anthropic API with the given messages and generation kwargs.

        :param messages: A list of ChatMessage instances representing the input messages.
            If a string is provided, it is converted to a list containing a ChatMessage with user role.
        :param streaming_callback: A callback function that is called when a new token is received from the stream.
        :param generation_kwargs: Optional arguments to pass to the Anthropic generation endpoint.
        :param tools: A list of Tool and/or Toolset objects, or a single Toolset, that the model can use.
        Each tool should have a unique name. If set, it will override the `tools` parameter set during component
        initialization.
        :returns: A dictionary with the following keys:
            - `replies`: The responses from the model
        """
        messages = _normalize_messages(messages)
        system_messages, non_system_messages, generation_kwargs, anthropic_tools = self._prepare_request_params(
            messages, generation_kwargs, tools
        )

        streaming_callback = select_streaming_callback(
            init_callback=self.streaming_callback,
            runtime_callback=streaming_callback,
            requires_async=True,
        )

        response = await self.async_client.messages.create(
            model=self.model,
            messages=non_system_messages,
            system=system_messages,
            tools=anthropic_tools,
            stream=streaming_callback is not None,
            max_tokens=generation_kwargs.pop("max_tokens", 1024),
            **generation_kwargs,
        )

        return await self._process_response_async(response, streaming_callback)
