loaders:
  - modules:
      - haystack_integrations.document_stores.ibm.document_store
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Ibm integration for Haystack
  id: integrations-ibm
  filename: ibm.md
  title: Ibm
