loaders:
  - modules:
      - haystack_integrations.components.converters.gotenberg.converter
    search_path: [../src]
processors:
  - type: filter
    documented_only: true
    skip_empty_modules: true
renderer:
  description: Gotenberg integration for Haystack
  id: integrations-gotenberg
  filename: gotenberg.md
  title: Gotenberg
