# SPDX-FileCopyrightText: 2023-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0

from typing import Any

from haystack import component, default_from_dict, default_to_dict
from haystack.dataclasses import Document
from haystack.document_stores.types import FilterPolicy
from haystack.document_stores.types.filter_policy import apply_filter_policy

from haystack_integrations.document_stores.elasticsearch.document_store import ElasticsearchDocumentStore


@component
class ElasticsearchInferenceDenseRetriever:
    """
    ElasticsearchInferenceDenseRetriever retrieves documents using Elasticsearch server-side dense vector inference.

    Unlike ``ElasticsearchEmbeddingRetriever``, no local embedding model is required — the query embedding
    is generated by an Elasticsearch inference endpoint (e.g. a text embedding model deployed via the
    Elastic Inference API such as ``".multilingual-e5-small-elasticsearch"`` on Serverless or a
    custom endpoint on a stateful cluster).

    Usage example:

    ```python
    from haystack_integrations.document_stores.elasticsearch import ElasticsearchDocumentStore
    from haystack_integrations.components.retrievers.elasticsearch import ElasticsearchInferenceDenseRetriever

    document_store = ElasticsearchDocumentStore(hosts="https://my-cluster.es.io:443")
    retriever = ElasticsearchInferenceDenseRetriever(
        document_store=document_store,
        inference_id=".multilingual-e5-small-elasticsearch",
    )

    result = retriever.run(query="Find documents about Berlin")
    for doc in result["documents"]:
        print(doc.content)
    ```
    """

    def __init__(
        self,
        *,
        document_store: ElasticsearchDocumentStore,
        inference_id: str,
        filters: dict[str, Any] | None = None,
        top_k: int = 10,
        num_candidates: int | None = None,
        filter_policy: str | FilterPolicy = FilterPolicy.REPLACE,
    ) -> None:
        """
        Create the ElasticsearchInferenceDenseRetriever component.

        :param document_store: An instance of ElasticsearchDocumentStore.
        :param inference_id: The Elasticsearch inference endpoint ID used to embed the query text.
        :param filters: Filters applied to the retrieved Documents.
        :param top_k: Maximum number of Documents to return.
        :param num_candidates: Number of approximate kNN candidates per shard. Defaults to ``top_k * 10``.
        :param filter_policy: Policy to determine how filters are applied.
        :raises ValueError: If ``document_store`` is not an instance of ``ElasticsearchDocumentStore`` or
            ``inference_id`` is empty.
        """
        if not isinstance(document_store, ElasticsearchDocumentStore):
            msg = "document_store must be an instance of ElasticsearchDocumentStore"
            raise ValueError(msg)

        if not inference_id:
            msg = "inference_id must be provided"
            raise ValueError(msg)

        self._document_store = document_store
        self._inference_id = inference_id
        self._filters = filters or {}
        self._top_k = top_k
        self._num_candidates = num_candidates
        self._filter_policy = FilterPolicy.from_str(filter_policy) if isinstance(filter_policy, str) else filter_policy

    def to_dict(self) -> dict[str, Any]:
        """
        Serializes the component to a dictionary.

        :returns: Dictionary with serialized data.
        """
        return default_to_dict(
            self,
            document_store=self._document_store.to_dict(),
            inference_id=self._inference_id,
            filters=self._filters,
            top_k=self._top_k,
            num_candidates=self._num_candidates,
            filter_policy=self._filter_policy.value,
        )

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ElasticsearchInferenceDenseRetriever":
        """
        Deserializes the component from a dictionary.

        :param data: Dictionary to deserialize from.
        :returns: Deserialized component.
        """
        data["init_parameters"]["document_store"] = ElasticsearchDocumentStore.from_dict(
            data["init_parameters"]["document_store"]
        )
        if filter_policy := data["init_parameters"].get("filter_policy"):
            data["init_parameters"]["filter_policy"] = FilterPolicy.from_str(filter_policy)
        return default_from_dict(cls, data)

    @component.output_types(documents=list[Document])
    def run(
        self,
        query: str,
        filters: dict[str, Any] | None = None,
        top_k: int | None = None,
    ) -> dict[str, list[Document]]:
        """
        Retrieve documents using inference-based dense vector search.

        :param query: Query text to embed and search with.
        :param filters: Filters applied when fetching documents from the Document Store.
            The way runtime filters are applied depends on the ``filter_policy`` selected when
            initializing the Retriever.
        :param top_k: Maximum number of documents to return.
        :returns: A dictionary with the following keys:
            - ``documents``: List of ``Document``s most similar to the given ``query``
        """
        filters = apply_filter_policy(self._filter_policy, self._filters, filters)
        docs = self._document_store._dense_retrieval_inference(
            query=query,
            inference_id=self._inference_id,
            filters=filters,
            top_k=top_k or self._top_k,
            num_candidates=self._num_candidates,
        )
        return {"documents": docs}

    @component.output_types(documents=list[Document])
    async def run_async(
        self,
        query: str,
        filters: dict[str, Any] | None = None,
        top_k: int | None = None,
    ) -> dict[str, list[Document]]:
        """
        Asynchronously retrieve documents using inference-based dense vector search.

        :param query: Query text to embed and search with.
        :param filters: Filters applied when fetching documents from the Document Store.
            The way runtime filters are applied depends on the ``filter_policy`` selected when
            initializing the Retriever.
        :param top_k: Maximum number of documents to return.
        :returns: A dictionary with the following keys:
            - ``documents``: List of ``Document``s most similar to the given ``query``
        """
        filters = apply_filter_policy(self._filter_policy, self._filters, filters)
        docs = await self._document_store._dense_retrieval_inference_async(
            query=query,
            inference_id=self._inference_id,
            filters=filters,
            top_k=top_k or self._top_k,
            num_candidates=self._num_candidates,
        )
        return {"documents": docs}
