# SPDX-FileCopyrightText: 2026-present deepset GmbH <info@deepset.ai>
#
# SPDX-License-Identifier: Apache-2.0

"""Experimental operating and harness-optimization APIs for Agent Pack."""

from haystack_integrations.agent_pack.optimization.campaign import (
    ApprovedModelRecipeProposer,
    CampaignJournal,
    CampaignRecommendation,
    CampaignResult,
    CandidateEvaluation,
    EvaluationMetrics,
    HarnessEvaluator,
    HarnessOptimizationCampaign,
    HarnessOptimizerAgentProposer,
    IsolatedHarnessEvaluator,
    OptimizationObjectives,
    RecipeProposer,
)
from haystack_integrations.agent_pack.optimization.optimizer_agent import (
    HAYSTACK_DOCS_MCP_URL,
    bundled_agent_building_skills_path,
    create_harness_optimizer_agent,
    create_haystack_docs_toolset,
)
from haystack_integrations.agent_pack.optimization.policy import (
    POLICY_DECISIONS_CONTEXT_KEY,
    ApprovedAssetCatalog,
    AssetValidation,
    ModelAsset,
    PolicyEnforcementStrategy,
    PolicyEvaluation,
    PolicyProvider,
    StaticPolicyProvider,
    ToolAsset,
)
from haystack_integrations.agent_pack.optimization.recipes import (
    CandidateRecipe,
    CompositeRecipe,
    ModelSubstitutionRecipe,
    PromptAndGenerationRecipe,
    RegisteredStructuralRecipe,
    SpecialistDelegationRecipe,
    StructuralRecipeRegistry,
    ToolSelectionRecipe,
    recipe_fingerprint,
    recipe_from_dict,
)
from haystack_integrations.agent_pack.optimization.tracing import (
    CapturedAgentRun,
    CapturedRun,
    LocalTraceCollector,
    LocalTraceStore,
    RunCaptureTracer,
    TraceArtifact,
    TraceCapturingAgentRunner,
    TraceSelection,
    TraceSource,
    extract_agent_reference_output,
    extract_agent_replay_inputs,
)

__all__ = [
    "HAYSTACK_DOCS_MCP_URL",
    "POLICY_DECISIONS_CONTEXT_KEY",
    "ApprovedAssetCatalog",
    "ApprovedModelRecipeProposer",
    "AssetValidation",
    "CampaignJournal",
    "CampaignRecommendation",
    "CampaignResult",
    "CandidateEvaluation",
    "CandidateRecipe",
    "CapturedAgentRun",
    "CapturedRun",
    "CompositeRecipe",
    "EvaluationMetrics",
    "HarnessEvaluator",
    "HarnessOptimizationCampaign",
    "HarnessOptimizerAgentProposer",
    "IsolatedHarnessEvaluator",
    "LocalTraceCollector",
    "LocalTraceStore",
    "ModelAsset",
    "ModelSubstitutionRecipe",
    "OptimizationObjectives",
    "PolicyEnforcementStrategy",
    "PolicyEvaluation",
    "PolicyProvider",
    "PromptAndGenerationRecipe",
    "RecipeProposer",
    "RegisteredStructuralRecipe",
    "RunCaptureTracer",
    "SpecialistDelegationRecipe",
    "StaticPolicyProvider",
    "StructuralRecipeRegistry",
    "ToolAsset",
    "ToolSelectionRecipe",
    "TraceArtifact",
    "TraceCapturingAgentRunner",
    "TraceSelection",
    "TraceSource",
    "bundled_agent_building_skills_path",
    "create_harness_optimizer_agent",
    "create_haystack_docs_toolset",
    "extract_agent_reference_output",
    "extract_agent_replay_inputs",
    "recipe_fingerprint",
    "recipe_from_dict",
]
