# This workflow comes from https://github.com/ofek/hatch-mypyc
# https://github.com/ofek/hatch-mypyc/blob/5a198c0ba8660494d02716cfc9d79ce4adfb1442/.github/workflows/test.yml
name: Test / chroma

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - 'integrations/chroma/**'
      - '.github/workflows/chroma.yml'

defaults:
  run:
    working-directory: integrations/chroma

concurrency:
  group: chroma-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10']

    steps:
    - name: Support longpaths
      if: matrix.os == 'windows-latest'
      working-directory: .
      run: git config --system core.longpaths true

    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Hatch
      run: pip install --upgrade hatch

    - name: Lint
      if: matrix.python-version == '3.9' && runner.os == 'Linux'
      run: hatch run lint:all

    - name: Run tests
      run: hatch run cov