# This workflow comes from https://github.com/ofek/hatch-mypyc
# https://github.com/ofek/hatch-mypyc/blob/5a198c0ba8660494d02716cfc9d79ce4adfb1442/.github/workflows/test.yml
name: Test / elasticsearch

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - "integrations/elasticsearch/**"
      - ".github/workflows/elasticsearch.yml"

concurrency:
  group: elasticsearch-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Lint
        working-directory: integrations/elasticsearch
        if: matrix.python-version == '3.9'
        run: hatch run lint:all

      - name: Run ElasticSearch container
        working-directory: integrations/elasticsearch
        run: docker-compose up -d

      - name: Run tests
        working-directory: integrations/elasticsearch
        run: hatch run cov
