# This workflow comes from https://github.com/ofek/hatch-mypyc
# https://github.com/ofek/hatch-mypyc/blob/5a198c0ba8660494d02716cfc9d79ce4adfb1442/.github/workflows/test.yml
name: Test / openrouter

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - "integrations/openrouter/**"
      - "!integrations/openrouter/*.md"
      - ".github/workflows/openrouter.yml"

defaults:
  run:
    working-directory: integrations/openrouter

concurrency:
  group: openrouter-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

jobs:
  run:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.13"]

    steps:
      - name: Support longpaths
        if: matrix.os == 'windows-latest'
        working-directory: .
        run: git config --system core.longpaths true

      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pip install --upgrade hatch

    # TODO: Once this integration is properly typed, use hatch run test:types
    # https://github.com/deepset-ai/haystack-core-integrations/issues/1771
      - name: Lint
        if: matrix.python-version == '3.9' && runner.os == 'Linux'
        run: hatch run fmt-check && hatch run lint:typing

      - name: Generate docs
        if: matrix.python-version == '3.9' && runner.os == 'Linux'
        run: hatch run docs

      - name: Run tests
        run: hatch run test:cov-retry

      - name: Run unit tests with lowest direct dependencies
        run: |
          hatch run uv pip compile pyproject.toml --resolution lowest-direct --output-file requirements_lowest_direct.txt
          hatch run uv pip install -r requirements_lowest_direct.txt
          hatch run test:unit

      - name: Nightly - run unit tests with Haystack main branch
        if: github.event_name == 'schedule'
        run: |
          hatch env prune
          hatch run uv pip install git+https://github.com/deepset-ai/haystack.git@main
          hatch run test:unit

      - name: Send event to Datadog for nightly failures
        if: failure() && github.event_name == 'schedule'
        uses: ./.github/actions/send_failure
        with:
          title: |
            Core integrations nightly tests failure: ${{ github.workflow }}
          api-key: ${{ secrets.CORE_DATADOG_API_KEY }}
