# This workflow comes from https://github.com/ofek/hatch-mypyc
# https://github.com/ofek/hatch-mypyc/blob/5a198c0ba8660494d02716cfc9d79ce4adfb1442/.github/workflows/test.yml
name: Test / optimum

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    paths:
      - "integrations/optimum/**"
      - ".github/workflows/optimum.yml"

defaults:
  run:
    working-directory: integrations/optimum

concurrency:
  group: optimum-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"

jobs:
  run:
    name: Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10"]

    steps:
      - name: Support longpaths
        if: matrix.os == 'windows-latest'
        working-directory: .
        run: git config --system core.longpaths true

      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pip install --upgrade hatch

      - name: Lint
        if: matrix.python-version == '3.9' && runner.os == 'Linux'
        run: hatch run lint:all

      - name: Generate docs
        if: matrix.python-version == '3.9' && runner.os == 'Linux'
        run: hatch run docs

      - name: Run tests
        id: tests
        run: hatch run cov

      - name: Nightly - run unit tests with Haystack main branch
        if: github.event_name == 'schedule'
        id: nightly-haystack-main
        run: |
          hatch run pip install git+https://github.com/deepset-ai/haystack.git
          hatch run test -m "not integration"
      
      - name: Send event to Datadog for nightly failures
        if: failure() && github.event_name == 'schedule'
        uses: ./.github/actions/send_failure
        with:
          title: |
            core-integrations failure: 
            ${{ (steps.tests.conclusion == 'nightly-haystack-main') && 'nightly-haystack-main' || 'tests' }}
             - ${{ github.workflow }}
          api-key: ${{ secrets.CORE_DATADOG_API_KEY }}