name: Project release on PyPi

# The pushed tag must be formatted like so:
# * nodes/speech2text-v1.0.0
# * stores/foo-documentstore-v1.2.3
#
# The first part must be the path of the project being released.
# If we want to release version 1.0.0 of project text2speech
# that lives in path nodes/text2speech we'd have to push a
# nodes/text2speech-v1.0.0 tag.

on:
  push:
    tags:
      - "**-v[0-9].[0-9]+.[0-9]+"

jobs:
  release-on-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Hatch
        run: pip install hatch

      - name: Get project folder
        id: pathfinder
        shell: python
        run: |
          import os
          project_path = "${{ github.ref_name }}".rsplit("-", maxsplit=1)[0]
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            print(f'project_path={project_path}', file=f)

      - name: Build extra
        working-directory: ${{ steps.pathfinder.outputs.project_path }}
        run: hatch build

      - name: Publish on PyPi
        working-directory: ${{ steps.pathfinder.outputs.project_path }}
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_API_TOKEN }}
        run: hatch publish -y
